export const GET_SINGLE_USER = "GET_SINGLE_USER";

export const MAIN_LOADER = "MAIN_LOADER";

export const REGISTER_LOGIN_SIGNOUT_USER = "REGISTER_LOGIN_SIGNOUT_USER";

export const FIREBASE_LOADER = "FIREBASE_LOADER";

export const CREATE_TRIP = "CREATE_TRIP";