export const GET_SINGLE_USER = "GET_SINGLE_USER"

export const MAIN_LOADER = "MAIN_LOADER"

export const REGISTER_LOGIN_SIGNOUT_USER = "REGISTER_LOGIN_SIGNOUT_USER"

export const FIREBASE_LOADER = "FIREBASE_LOADER"

export const CREATE_TRIP = "CREATE_TRIP"

export const UPDATE_USER_DATA = "UPDATE_USER_DATA"

export const UPDATE_TRIP_DATA = "UPDATE_TRIP_DATA"

export const GET_ALL_TRIPS = "GET_ALL_TRIPS"

export const JOIN_TRIP = "JOIN_TRIP"

export const COMMENT_ON_TRIP = 'COMMENT_ON_TRIP'